shell = "/usr/bin/zsh"

[window]
decorations = "None"
startup_mode = "Fullscreen"

opacity = 0.8
blur = true

[font]
normal.family = 'DejaVuSansM Nerd Font Mono'
size =  14

[env]
TERM = 'xterm-256color'
