import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "/usr/bin/zsh"

[window]
decorations = "None"
startup_mode = "Fullscreen"

opacity = 0.9
blur = true

[font]
normal.family = 'Iosevka Nerd Font'
