import = [
  # curl -LO --output-dir ~/.config/alacritty https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
  "~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "/usr/bin/zsh"

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 5 }

[font]
normal.family = 'Iosevka Nerd Font'
size = 11.2

[mouse]
hide_when_typing = true
