- name: Install necessery packages
  hosts: targets
  tags: packages

  tasks:
    - name: Install git
      become: true
      ansible.builtin.apt:
        name: git
        state: present

    - name: Install make
      become: true
      ansible.builtin.apt:
        name: make
        state: present

    - name: Add unstable neovim repo
      become: true
      apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present

    - name: Install neovim=latest
      become: true
      ansible.builtin.apt:
        name: neovim
        state: latest

    - name: Install tmux
      become: true
      ansible.legacy.apt:
        name: tmux

    - name: Install gcc compiler
      become: true
      ansible.legacy.apt:
        name: gcc

    - name: Install ripgrep
      become: true
      ansible.legacy.apt:
        name: ripgrep

    - name: Install fd-find
      become: true
      ansible.legacy.apt:
        name: fd-find

- name: Fetch and install dotfiles
  hosts: targets
  tags: dotfiles

  tasks:
    - name: Clone dotfile repo
      ansible.builtin.git:
        repo: https://github.com/kanigreg/dotfiles.git
        dest: ~/dotfiles/
        single_branch: yes
        version: cloud
        force: yes
      notify:
        - Make link to neovim sources
        - Make link to tmux config

    - name: Clone tmux plugin manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

  handlers:
    - name: Make link to tmux config
      ansible.builtin.shell:
        cmd: make configure_tmux
        executable: /bin/bash
        chdir: ~/dotfiles/

    - name: Make link to neovim sources
      ansible.builtin.shell:
        cmd: make configure_neovim
        executable: /bin/bash
        chdir: ~/dotfiles/

