- name: Install necessery packages
  hosts: targets
  tags: packages

  tasks:
    - name: Install git
      become: true
      ansible.builtin.apt:
        name: git
        state: present

    - name: Install make
      become: true
      ansible.builtin.apt:
        name: make
        state: present

    - name: Add unstable neovim repo
      become: true
      apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present

    - name: Install neovim=latest
      become: true
      ansible.builtin.apt:
        name: neovim
        state: latest

- name: Fetch and install dotfiles
  hosts: targets
  tags: dotfiles

  tasks:
    - name: Fetch dotfile repo
      ansible.builtin.git:
        repo: https://github.com/kanigreg/dotfiles.git
        dest: ~/dotfiles/
        single_branch: yes
        version: cloud
      notify:
        - Make link to neovim sources

  handlers:
    - name: Make link to neovim sources
      ansible.builtin.shell:
        cmd: make install
        executable: /bin/bash
        chdir: ~/dotfiles/

