# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1E1E2E,spinner:#F5E0DC,hl:#F38BA8 \
--color=fg:#CDD6F4,header:#F38BA8,info:#CBA6F7,pointer:#F5E0DC \
--color=marker:#B4BEFE,fg+:#CDD6F4,prompt:#CBA6F7,hl+:#F38BA8 \
--color=selected-bg:#45475A \
--color=border:#6C7086,label:#CDD6F4"


export HISTIGNORE="ls*:*secret*:*password*"
export HISTCONTROL=ignoreboth

# tmux
alias t='tmuxinator'
alias ts='tmuxinator start'

# k8s
source <(kubectl completion bash)
alias k='kubectl'
alias kd='kubectl -n dev01'
alias kq='kubectl -n qa01'
alias krc='kubectl -n rc01'
alias kr='kubectl -n release'
complete -o default -F __start_kubectl k
complete -o default -F __start_kubectl kd
complete -o default -F __start_kubectl kq
complete -o default -F __start_kubectl krc
complete -o default -F __start_kubectl kr
