- name: Fetch and install dotfiles
  hosts: targets
  tags: dotfiles

  tasks:
    - name: Clone dotfile repo
      ansible.builtin.git:
        repo: https://github.com/kanigreg/dotfiles.git
        dest: ~/dotfiles/
        single_branch: yes
        version: cloud
        force: yes
      notify:
        - Make link to neovim sources
        - Make link to tmux config
        - Copy zshrc file

    - name: Clone tmux plugin manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

    - name: Clone zsh theme
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.zsh/powerlevel10k

    - name: Clone zsh syntax highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.zsh/syntax-highlighting

    - name: Clone zsh autosuggestion plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.zsh/autosuggestion

    - name: Clone fzf-git script
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf-git.sh
        dest: ~/.zsh/fzf-git

  handlers:
    - name: Make link to tmux config
      ansible.builtin.file:
        src: ~/dotfiles/tmux/.tmux.conf
        dest: ~/.tmux.conf
        state: link
        force: true

    - name: Make link to neovim sources
      ansible.builtin.file:
        src: ~/dotfiles/nvim/
        dest: ~/.config/nvim
        state: link
        force: true

    - name: Copy zshrc file
      ansible.builtin.copy:
        src: ~/dotfiles/zsh/.zshrc
        dest: ~/.zshrc
        remote_src: true
        force: true
