- name: Fetch and install dotfiles
  hosts: targets
  tags: dotfiles

  tasks:
    - name: Clone dotfile repo
      ansible.builtin.git:
        repo: https://github.com/kanigreg/dotfiles.git
        dest: ~/dotfiles/
        single_branch: yes
        version: cloud
        force: yes
      notify:
        - Make link to neovim sources
        - Make link to tmux config
        - Make link to zshrc

    - name: Clone tmux plugin manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

    - name: Clone zsh theme
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.zsh/powerlevel10k

    - name: Clone zsh syntax highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.zsh/syntax-highlighting

    - name: Clone zsh autosuggestion plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.zsh/autosuggestion

  handlers:
    - name: Make link to tmux config
      ansible.builtin.shell:
        cmd: make configure_tmux
        executable: /bin/bash
        chdir: ~/dotfiles/

    - name: Make link to neovim sources
      ansible.builtin.shell:
        cmd: make configure_neovim
        executable: /bin/bash
        chdir: ~/dotfiles/
    
    - name: Make link to zshrc
      ansible.builtin.file:
        src: ~/dotfiles/zsh/.zshrc
        dest: ~/.zshrc
        state: link
