- name: Fetch and install dotfiles
  hosts: targets
  tags: dotfiles

  tasks:
    - name: Clone dotfile repo
      ansible.builtin.git:
        repo: https://github.com/kanigreg/dotfiles.git
        dest: ~/dotfiles/
        single_branch: yes
        version: cloud
        force: yes
      notify:
        - Make link to neovim sources
        - Make link to tmux config

    - name: Clone tmux plugin manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

  handlers:
    - name: Make link to tmux config
      ansible.builtin.shell:
        cmd: make configure_tmux
        executable: /bin/bash
        chdir: ~/dotfiles/

    - name: Make link to neovim sources
      ansible.builtin.shell:
        cmd: make configure_neovim
        executable: /bin/bash
        chdir: ~/dotfiles/

