- name: Install necessery packages
  hosts: targets
  tags: packages

  tasks:
    - name: Install git
      become: true
      ansible.builtin.apt:
        name: git
        state: present

    - name: Install make
      become: true
      ansible.builtin.apt:
        name: make
        state: present

    - name: Add unstable neovim repo
      become: true
      apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present

    - name: Install neovim=latest
      become: true
      ansible.builtin.apt:
        name: neovim
        state: latest

    - name: Install tmux
      become: true
      ansible.builtin.apt:
        name: tmux

    - name: Install gcc compiler
      become: true
      ansible.builtin.apt:
        name: gcc

    - name: Install ripgrep
      become: true
      ansible.builtin.apt:
        name: ripgrep

    - name: Install fd-find
      become: true
      ansible.builtin.apt:
        name: fd-find

    - name: Install zsh
      become: true
      ansible.builtin.apt:
        name: zsh
