- name: Install necessery packages
  hosts: targets
  tags: packages

  tasks:
    - name: Add unstable neovim repo
      become: true
      apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present

    - name: Install neovim=latest
      become: true
      ansible.builtin.apt:
        name: neovim
        state: latest

    - name: Install necessery packages
      become: true
      ansible.builtin.apt:
        pkg:
          - make
          - git
          - tmux
          - gcc
          - ripgrep
          - fd-find
          - zsh

    - name: Download and install fzf (from dep pkg)
      become: true
      ansible.builtin.apt:
        deb: https://launchpad.net/ubuntu/+archive/primary/+files/fzf_0.46.1-1_amd64.deb

    - name: Download and install bat (from dep pkg)
      become: true
      ansible.builtin.apt:
        deb: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat_0.24.0_amd64.deb
      notify:
        - Donwload bat theme

    - name: Download and install git-delta (from dep pkg)
      become: true
      ansible.builtin.apt:
        deb: https://github.com/dandavison/delta/releases/download/0.17.0/git-delta_0.17.0_amd64.deb

    - name: Download and unarchive lazygit
      ansible.builtin.unarchive:
        src: https://github.com/jesseduffield/lazygit/releases/download/v0.41.0/lazygit_0.41.0_Linux_x86_64.tar.gz
        dest: /tmp
        remote_src: true
      notify:
        Install lazygit

  handlers:
    - name: Download bat theme
      ansible.builtin.get_url:
        url: https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme
        dest: ~/.config/bat/themes

    - name: Install lazygit
      become: true
      ansible.builtin.shell:
        cmd: install lazygit /usr/local/bin
        chdir: /tmp
