- name: Ruby
  hosts: targets
  tags: ruby

  tasks:
    - name: Install necessery packages
      become: true
      ansible.builtin.apt:
        pkg:
        - autoconf
        - patch
        - build-essential
        - rustc
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libgmp-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm6
        - libgdbm-dev
        - libdb-dev
        - uuid-dev

    - name: Add ruby plugin into asdf
      ansible.builtin.command:
        argv:
          - ~/.asdf/bin/asdf
          - plugin
          - add
          - ruby
          - https://github.com/asdf-vm/asdf-ruby.git

    - name: Install latest ruby version
      ansible.builtin.command:
        argv:
          - ~/.asdf/bin/asdf
          - install
          - ruby
          - latest

    - name: Set latest ruby as global version
      ansible.builtin.command:
        argv:
          - ~/.asdf/bin/asdf
          - global
          - ruby
          - latest

- name: Docker
  hosts: targets
  tags: docker

  tasks:
    - name: Check if docker is installed
      command: docker --version
      register: docker_present
      ignore_errors: true

    - name: Download installation script
      when: docker_present.failed
      ansible.builtin.get_url: 
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "0755"

    - name: Install docker
      when: docker_present.failed
      become: true
      ansible.builtin.command: /tmp/get-docker.sh
      notify:
        - Ensure group "docker" exists
        - Append to docker group


    - name: Append to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        append: true
        groups: 
          - docker

  handlers:
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present




